fix: duplicate actor when multiple roles
RUC-MSc-CS-CIT-2024/portfolio_subproject_3 pull request #127
Opened 2024-12-13 09:12 UTC by idax6797

This pull request includes changes to the `MediaDetailPage` and `PersonsCarousel` components to improve crew and cast members' handling and display of roles. The most important changes include introducing a new function to merge roles, updating how roles are displayed, and conditional rendering of tabs.

Enhancements to role handling and display:

* [`src/frontend/src/components/PersonsCarousel/PersonsCarousel.jsx`](diffhunk://#diff-f124bc23b307bb6de3f29438dcd1a02ed871c1c0743fde0a59d89fa672aeb3bbL14-R14): Updated the `role` prop to handle arrays by joining them into a string.
* [`src/frontend/src/pages/MediaDetailPage.jsx`](diffhunk://#diff-9067da5199ca855ad6e34c7c96e7704c01a34040a5826da405606ca2edcb83ecR39-R62): Added a new `mergeRoles` function to merge roles for crew and cast members into arrays, ensuring unique roles are combined.
* [`src/frontend/src/pages/MediaDetailPage.jsx`](diffhunk://#diff-9067da5199ca855ad6e34c7c96e7704c01a34040a5826da405606ca2edcb83ecR126-R127): Updated the `MediaDetailPage` component to use `mergedCrew` and `mergedCast` for the `PersonsCarousel` components, ensuring roles are properly merged and displayed. [[1]](diffhunk://#diff-9067da5199ca855ad6e34c7c96e7704c01a34040a5826da405606ca2edcb83ecR126-R127) [[2]](diffhunk://#diff-9067da5199ca855ad6e34c7c96e7704c01a34040a5826da405606ca2edcb83ecR168-R171) [[3]](diffhunk://#diff-9067da5199ca855ad6e34c7c96e7704c01a34040a5826da405606ca2edcb83ecR181-R185) [[4]](diffhunk://#diff-9067da5199ca855ad6e34c7c96e7704c01a34040a5826da405606ca2edcb83ecR195)

2024-12-13 10:11 UTC, sofushn requested changes

2024-12-13 10:11 UTC, sofushn commented on src/frontend/src/components/PersonsCarousel/PersonsCarousel.jsx
>      />
The character the person plays should also be shown when its as a cast member on the media page

2024-12-13 19:07 UTC, sofushn commented
Something is still wrong, should display all characters that the person have played, e.g. Christian Bale is playing `Bruce Wayne` and `Batman`

![image](https://github.com/user-attachments/assets/004787fd-2712-461b-8730-406b42283e0e)

2024-12-14 08:26 UTC, idax6797 commented
> Something is still wrong, should display all characters that the person have played, e.g. Christian Bale is playing `Bruce Wayne` and `Batman`
> 
> ![image](https://private-user-images.githubusercontent.com/19843915/395670371-004787fd-2712-461b-8730-406b42283e0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxNjUwNjgsIm5iZiI6MTczNDE2NDc2OCwicGF0aCI6Ii8xOTg0MzkxNS8zOTU2NzAzNzEtMDA0Nzg3ZmQtMjcxMi00NjFiLTg3MzAtNDA2YjQyMjgzZTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDA4MjYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlMWNmOTIxMzZmNGQ0ODNjYWI1Y2ExOTYwNWU4ODVlODA0Zjk1ZDlmMDBlZDE3MWRhMzlkNzk5ZTY5MWQ1ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xOV_73a6ZHqf6UlYaLpRo94cg_WtuqUPjkGFPM40NvQ)

Yes this is correct, did not think of this. I have now adjusted this to be an array. :)

2024-12-14 13:53 UTC, sofushn approved these changes

2024-12-14 14:12 UTC, merged