feat: set up single media page and fetch content
RUC-MSc-CS-CIT-2024/portfolio_subproject_3 pull request #70
Opened 2024-12-03 20:52 UTC by idax6797

This pull request includes several enhancements and refactoring changes to the media-related components and services in the frontend application. The most important changes include updating the `MediaDetailPage` to fetch data dynamically, refactoring `MediaInformation` to handle new data structures, and improving the `Rating` component to display additional information.

Enhancements to data fetching and display:

* [`src/frontend/src/pages/MediaDetailPage.jsx`](diffhunk://#diff-9067da5199ca855ad6e34c7c96e7704c01a34040a5826da405606ca2edcb83ecL1-R134): Updated to dynamically fetch media data, titles, crew, similar media, and releases using new service functions. Added error handling and loading state management.
* [`src/frontend/src/services/mediaService.js`](diffhunk://#diff-337b1594ea5513a006c2589f5ce02e2b7ba67fdb8be37b75ced9be883c1b4dcfL1-L11): Implemented new service functions to fetch media data, titles, crew, similar media, and releases from the API.

Refactoring and improvements to components:

* [`src/frontend/src/components/MediaInformation/MediaInformation.jsx`](diffhunk://#diff-1c6dba6e61786d471185066fa8b0804d3e551ce373e9ebaddaa916c075dbae12R12-R24): Refactored to use new data structures for `posterUri`, `releaseDate`, `runtimeMinutes`, `writer`, `producer`, and `scores`. Added a helper function to render `InfoRow` with a separator. [[1]](diffhunk://#diff-1c6dba6e61786d471185066fa8b0804d3e551ce373e9ebaddaa916c075dbae12R12-R24) [[2]](diffhunk://#diff-1c6dba6e61786d471185066fa8b0804d3e551ce373e9ebaddaa916c075dbae12R34-R56) [[3]](diffhunk://#diff-1c6dba6e61786d471185066fa8b0804d3e551ce373e9ebaddaa916c075dbae12L51-R72) [[4]](diffhunk://#diff-1c6dba6e61786d471185066fa8b0804d3e551ce373e9ebaddaa916c075dbae12L73-R94) [[5]](diffhunk://#diff-1c6dba6e61786d471185066fa8b0804d3e551ce373e9ebaddaa916c075dbae12L117-R157)
* [`src/frontend/src/components/Rating/Rating.jsx`](diffhunk://#diff-952c6b33e1548b29ee68b2999a7039d6c02e057835bf1fdf45df32d408a43e9aR4-R17): Enhanced to handle cases where ratings are not available and to display additional information such as vote count.

CSS and UI adjustments:

* [`src/frontend/src/components/MediaCard/MediaCard.css`](diffhunk://#diff-6a7de71321ffb8b6201b1b9d9d71cc6a86a26385279bf5b6a1399481e8e91637R15-R20): Added styles for `.card-img` to ensure images cover the card area properly.
* [`src/frontend/src/components/MediaInformation/MediaInformation.css`](diffhunk://#diff-bfc6fb4fb15c098fadf25b28a6af486f6d443147a64b1cf939af7c8958d0e89dL26-R43): Added styles for `.img-media-information` and adjusted media queries for better responsiveness.

Helper functions:

* [`src/frontend/src/utils/date.js`](diffhunk://#diff-ff6676296a127a9f9e7b799962d36b7dd7c87a6805e2c8f826c6b7a56ae70511R1-R5): Added a `formatDate` function to format date strings in a more readable manner.
* [`src/frontend/src/utils/extractCrew.js`](diffhunk://#diff-dcb955a259e725d5e13927c87b3e4eb6f8b7be21cd2b13fb12e9781a4896e2c2R1-R29): Added functions to extract directors, writers, and producers from the crew data.

2024-12-03 22:34 UTC, sofushn requested changes

2024-12-03 22:34 UTC, sofushn commented on src/frontend/src/components/MediaInformation/MediaInformation.jsx
> +                    )}
I feel like this would be better if it was a component instead of a function

2024-12-03 22:34 UTC, sofushn commented on src/frontend/src/utils/extractCrew.js
Is there a reason for having this as a utils file and not just in the component where its used? Does it have to be reused?

2024-12-04 16:42 UTC, idax6797 commented on src/frontend/src/utils/extractCrew.js
No it is not reused. so it would make sense to have this on the page it is used. This would make the code self-contained and easier to understand, as all related logic is in one place. True 🚀

2024-12-04 19:21 UTC, sofushn approved these changes

2024-12-04 19:23 UTC, merged